version: '3.8'

services:
  books:
    build:
      context: ./books-service
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/booksdb

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
