version: '3.8'

services:
  books:
    build: ./books-service
    volumes:
      - ./books-service:/app
      - ./tests:/app/tests
    ports:
      - "5001:5001"
    depends_on:
      - non_existent_service  # This service does not exist, so it will fail
    environment:
      - MONGO_URI=mongodb://mongo:27017/booksdb

  mongo:
    image: mongo
    ports:
      - "27017:27017"
