version: '3.8'

services:
  books:
    build: ./books-service
    volumes:
      - ./books-service:/app
      - ./tests:/app/tests
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/booksdb
      - CRITICAL_VAR=   # Force the container to fail if this is empty or incorrect

  mongo:
    image: mongo
    ports:
      - "27017:27017"
