version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  books:
    build: ./books-service
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/booksdb
