name: assignment3

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build the Docker image
      run: docker build -t books-service ./books-service

    - name: Log build success
      run: echo "Image successfully built" >> log.txt

    - name: Upload log file
      uses: actions/upload-artifact@v4
      with:
        name: build-log
        path: log.txt

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Ensure port is available
      run: |
        sudo lsof -i :27017 && sudo kill -9 $(sudo lsof -t -i :27017) || echo "Port 27017 is available"

    - name: Build and start services
      run: |
        docker-compose up -d
        sleep 30

    - name: Wait for books service to be ready
      run: |
        until curl -s -f -o /dev/null http://localhost:5001/books; do
          echo "Waiting for books service..."
          sleep 5
        done
      shell: bash

    - name: Run tests
      run: |
        docker-compose exec books pytest -v tests/assn3_tests.py > assn3_test_results.txt
        cat assn3_test_results.txt
      shell: bash

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: assn3_test_results
        path: assn3_test_results.txt

  query:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Ensure port is available
      run: |
        sudo lsof -i :27017 && sudo kill -9 $(sudo lsof -t -i :27017) || echo "Port 27017 is available"

    - name: Build and start services
      run: |
        docker-compose up -d
        sleep 30

    - name: Wait for books service to be ready
      run: |
        until curl -s -f -o /dev/null http://localhost:5001/books; do
          echo "Waiting for books service..."
          sleep 5
        done
      shell: bash

    - name: Execute queries
      run: |
        echo "Starting query execution" >> log.txt
        if [ -f query.txt ]; then
          while IFS= read -r query; do
            echo "Executing query: ${query}" >> log.txt
            curl_output=$(curl -s -w "\n%{http_code}" -o response_body.txt "http://localhost:5001/books${query}")
            response=$(tail -n1 <<< "$curl_output")
            if [ "$response" -eq 200 ]; then
              cat response_body.txt >> response.txt
              echo -e "\nquery: ${query}\nresponse: $(<response_body.txt)" >> log.txt
            else
              echo -e "query: ${query}\nresponse: error $response" >> response.txt
              echo -e "query: ${query}\nresponse: error $response" >> log.txt
            fi
            cat response_body.txt >> log.txt  # Log the response body content
          done < query.txt
        fi
        ls -l >> log.txt  # List files after queries
      shell: bash

    - name: Upload response
      uses: actions/upload-artifact@v4
      with:
        name: response
        path: response.txt

    - name: Upload log
      uses: actions/upload-artifact@v4
      with:
        name: log
        path: log.txt
